# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Build ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --save-dev jest
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Testing
      run: npm test
      
    - name: Build Documentation
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./source
        config_file: conf.json
        recurse: true
        output_dir: ./out
        #template: minami
        front_page: DOCREADME.md
        
#     - name: Deployment
#       uses: JamesIves/github-pages-deploy-action@4.1.0
#       with:
#         branch: master
#         folder: ./source/pages
